[package]
name = "rust-start"
version = "0.1.0"
edition = "2024"

[dependencies]
# logging
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

# config
config = "0.15.19"

# errors
thiserror = "2.0.17"

# serde
serde = { version = "1.0.228", features = ["derive"] }
